version: '3.4'

services:
  myproject:
    image: myproject
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    # command: python manage.py runserver 127.0.0.1:80 
